openapi: 3.0.0
info:
  title: Plugin Metadata API
  version: 1.0.0

components:
  schemas:
    PluginMetadata:
      type: object
      properties:
        nameTag:
          type: string
          description: "Unique identifier for the plugin"
        version:
          type: string
          description: "Version of the plugin, following semantic versioning"
        executableFile:
          type: string
          description: "Path to the main executable file for the plugin"
        author:
          type: object
          description: "Information about the plugin's author"
          properties:
            name:
              type: string
              description: "Author's full name"
            email:
              type: string
              format: email
              description: "Author's email address"
          required:
            - name
            - email
        inputs:
          type: object
          description: "Input validation schema for the plugin"
          additionalProperties: true
        outputs:
          type: object
          description: "Output structure for the plugin"
          additionalProperties: true
        description:
          type: string
          description: "Brief description of the plugin's functionality"
      required:
        - nameTag
        - version
        - executableFile
        - author
        - inputs
        - description

paths:
  /plugin-metadata:
    get:
      summary: Get plugin metadata
      responses:
        '200':
          description: Returns plugin metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PluginMetadata'
