openapi: 3.0.0
info:
  title: Topic Mapping API
  version: 1.0.0

components:
  schemas:
    TopicMapping:
      type: object
      properties:
        topics:
          type: object
          properties:
            TASK_QUEUE:
              type: string
              description: "The queue where tasks are submitted"
            RESPONSE_QUEUE:
              type: string
              description: "The queue where responses to tasks are sent"
      required:
        - topics
