openapi: 3.0.0
info:
  title: Plugin Management API
  version: 1.0.0
servers:
- url: /
paths:
  /plugins:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PluginMetadata'
      responses:
        "201":
          description: Plugin successfully created
      summary: Upload a new plugin
  /plugins/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: Plugin successfully deleted
      summary: Delete a plugin by ID
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PluginMetadata'
          description: Returns plugin metadata
      summary: Get plugin metadata by ID
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PluginMetadata'
      responses:
        "200":
          description: Plugin metadata successfully updated
      summary: Update plugin metadata
  /plugins/{id}/images:
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_plugins__id__images_get_200_response'
          description: Returns all images of the plugin
      summary: Get all images of a plugin
    post:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/_plugins__id__images_post_request'
      responses:
        "201":
          description: Images successfully uploaded
      summary: Upload multiple images for a plugin
  /plugins/{id}/images/thumbnail:
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_plugins__id__images_thumbnail_put_request'
      responses:
        "200":
          description: Thumbnail successfully updated
      summary: Set or update the thumbnail image for a plugin
  /plugins/{id}/images/{filename}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: false
        in: path
        name: filename
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Image successfully deleted
      summary: Delete a specific image of a plugin
components:
  schemas:
    PluginMetadata:
      example:
        outputs:
          key: ""
        author:
          name: name
          email: email
        inputs:
          key: ""
        description: description
        version: version
        tags:
        - tags
        - tags
        executableFile: executableFile
        createdAt: 2000-01-23T04:56:07.000+00:00
        imageUrls:
        - https://openapi-generator.tech
        - https://openapi-generator.tech
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        status: active
        updatedAt: 2000-01-23T04:56:07.000+00:00
        thumbnailUrl: https://openapi-generator.tech
      properties:
        id:
          description: Unique identifier for the plugin
          format: uuid
          type: string
        version:
          description: "Version of the plugin, following semantic versioning"
          type: string
        executableFile:
          description: Path to the main executable file for the plugin
          type: string
        author:
          $ref: '#/components/schemas/PluginMetadata_author'
        inputs:
          additionalProperties: true
          description: Input validation schema for the plugin
          type: object
        outputs:
          additionalProperties: true
          description: Expected output from the plugin
          type: object
        description:
          description: Brief description of the plugin's functionality
          type: string
        status:
          description: The current status of the plugin
          enum:
          - active
          - deprecated
          - pending
          type: string
        createdAt:
          description: Timestamp when the plugin was first created
          format: date-time
          type: string
        updatedAt:
          description: Timestamp when the plugin was last updated
          format: date-time
          type: string
        tags:
          description: Tags associated with the plugin for easy categorization
          items:
            type: string
          type: array
        thumbnailUrl:
          description: URL of the thumbnail image
          format: uri
          type: string
        imageUrls:
          description: List of URLs for additional images
          items:
            format: uri
            type: string
          type: array
      required:
      - author
      - createdAt
      - description
      - executableFile
      - id
      - inputs
      - status
      - updatedAt
      - version
      type: object
    _plugins__id__images_get_200_response:
      example:
        imageUrls:
        - https://openapi-generator.tech
        - https://openapi-generator.tech
        thumbnailUrl: https://openapi-generator.tech
      properties:
        thumbnailUrl:
          description: URL of the thumbnail image
          format: uri
          type: string
        imageUrls:
          description: List of image URLs
          items:
            format: uri
            type: string
          type: array
      type: object
    _plugins__id__images_post_request:
      properties:
        images:
          description: Images to upload
          items:
            format: binary
            type: string
          type: array
      type: object
    _plugins__id__images_thumbnail_put_request:
      properties:
        thumbnailUrl:
          description: URL of the thumbnail image
          format: uri
          type: string
      type: object
    PluginMetadata_author:
      description: Information about the plugin's author
      example:
        name: name
        email: email
      properties:
        name:
          description: Author's full name
          type: string
        email:
          description: Author's email address
          format: email
          type: string
      required:
      - email
      - name
      type: object

