openapi: 3.0.0
info:
  title: Event Sourcing API
  version: 1.0.0
servers:
- url: /
components:
  schemas:
    EventMessage:
      properties:
        event_id:
          description: Unique identifier for the event
          type: string
        aggregate_id:
          description: ID of the entity (aggregate) that this event relates to
          type: string
        aggregate_type:
          description: "Type of the aggregate, e.g., 'plugin', 'user', etc."
          type: string
        version:
          default: 1
          description: Version of the aggregate's state after this event
          type: number
        event_type:
          description: "Type of the event, e.g., 'PLUGIN_RUN', 'USER_ACTION'"
          type: string
        event_schema_version:
          default: "1.0"
          description: Version of the event schema
          type: string
        source:
          description: "Origin or source of the event, typically the service name"
          type: string
        timestamp:
          description: ISO 8601 timestamp for when the event occurred
          format: date-time
          type: string
        payload:
          additionalProperties: true
          description: "Data related to the event, this varies depending on event\
            \ type"
          nullable: true
          type: object
        user_id:
          description: ID of the user initiating the event
          type: string
      required:
      - aggregate_id
      - event_id
      - event_schema_version
      - event_type
      - source
      - timestamp
      - version
      type: object

